# Generated by Django 5.2.5 on 2025-08-12 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Тема письма')),
                ('letter_body', models.TextField(verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'письмо',
                'verbose_name_plural': 'письма',
                'ordering': ['subject'],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Почта')),
                ('full_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ф.И.О.')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'получатель письма',
                'verbose_name_plural': 'получатели письма',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_send', models.DateTimeField(verbose_name='Время запуска')),
                ('end_send', models.DateTimeField(verbose_name='Время завершения')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('finished', 'Завершена')], default='created', max_length=100, verbose_name='Статус')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.letter', verbose_name='Письмо')),
                ('recipients', models.ManyToManyField(to='mail.recipient', verbose_name='Получатель')),
            ],
        ),
    ]
