# Generated by Django 5.2.5 on 2025-08-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_alter_mailing_options_mailingtry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingtry',
            name='smtp_response',
            field=models.TextField(verbose_name='Ответ ошибки SMTP-сервера'),
        ),
        migrations.AlterField(
            model_name='mailingtry',
            name='status',
            field=models.CharField(max_length=100, verbose_name='Статус рассылки'),
        ),
    ]
