# Generated by Django 5.2.5 on 2025-10-16 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_alter_letter_owner_alter_mailing_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['pk'], 'permissions': [('can_manage_mailing', 'Can manage mailing')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ['email'], 'permissions': [('can_manage_recipient', 'Can manage recipient')], 'verbose_name': 'получатель письма', 'verbose_name_plural': 'получатели письма'},
        ),
    ]
