# Generated by Django 5.2.5 on 2025-10-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0007_alter_mailing_options_alter_recipient_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='cycle',
            field=models.CharField(blank=True, choices=[('now', 'Мгновенная'), ('everyday', 'Ежедневная'), ('everyweek', 'Еженедельная'), ('everymonth', 'Ежемесячная')], max_length=100, null=True, verbose_name='Цикл рассылки'),
        ),
    ]
