# Generated by Django 5.2.5 on 2025-10-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_mailing_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='cycle',
            field=models.CharField(choices=[('now', 'Мгновенная'), ('everyday', 'Ежедневная'), ('everyweek', 'Еженедельная'), ('everymonth', 'Ежемесячная')], default=None, max_length=100, verbose_name='Цикл рассылки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailing',
            name='end_send',
            field=models.DateTimeField(verbose_name='Время завершения'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='first_send',
            field=models.DateTimeField(verbose_name='Время запуска'),
        ),
    ]
