# Generated by Django 5.2.5 on 2025-10-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0009_alter_mailing_cycle_alter_mailing_end_send_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Почта'),
        ),
    ]
